### ISSUE TITLE
Remove Optional[] in logs

### ISSUE THREAD

**Issue by theute** [quarkiverse/quarkus-logging-cloudwatch#109]
When a pod start it shows:

`INFO: Logging to log-group: Optional[policies-fedramp-stage] and log-stream: Optional[policies-engine-74fb84cb9c-q78mj]`

It should show:
`INFO: Logging to log-group: "policies-fedramp-stage" and log-stream: "policies-engine-74fb84cb9c-q78mj"

**Comment by bennetelli** [comment]
fixed.
