### ISSUE TITLE
Support additional credentials type

### ISSUE THREAD

**Issue by missourian55** [quarkiverse/quarkus-logging-cloudwatch#206]
Right now this plugin supports only the *static* credentials type where `access_key` and `secret_key` needs to provisioned in `application.properties`

Can you please add support for other credentials provider like quarkus s3 plugin?
`quarkus.s3.aws.credentials.type=default`
https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-s3.html#_configuring_s3_clients

**Comment by bennetelli** [comment]
Hey @missourian55 thanks for opening the issue :) of course I can :) but this could take some time.

**Comment by missourian55** [comment]
@bennetelli 
If we establish below dependency in the runtime module, we automatically inherit all the available Credential providers supported by Quarkus.
```xml
        <dependency>
            <groupId>io.quarkiverse.amazonservices</groupId>
            <artifactId>quarkus-amazon-common</artifactId>
        </dependency>
```
https://github.com/quarkiverse/quarkus-amazon-services/blob/main/common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AwsCredentialsProviderConfig.java

**Comment by bennetelli** [comment]
@missourian55 see #226

**Comment by bennetelli** [comment]
@missourian55 and see #227

**Comment by bennetelli** [comment]
@missourian55 I guess your issue has been resolved by the Pull Requests above. I would like to close this issue. Please let me know if you still need something :)

**Comment by mavanidipen365** [comment]
@bennetelli I've tried to use this extension with aws default credentials but this is not supported.

Also there is strict validation also.
https://github.com/quarkiverse/quarkus-logging-cloudwatch/blob/main/runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchConfig.java

Is there any work around to do that?

**Comment by bennetelli** [comment]
@mavanidipen365 I could add a new optional flag to disable this strict validation.

Can you tell me why you need aws default credentials? I've never seen people using default credentials. 
Which properties are affected by your "aws default credentials" usage?

**Comment by mavanidipen365** [comment]
@bennetelli We have deployed a Quarkus application on AWS Fargate containers. The application is connected to AWS queues and secret managers. The default credentials provider is used to authenticate the application with these services. Additionally, we leverage the Amazon ECS container credentials, which are loaded from the environment variable AWS_CONTAINER_CREDENTIALS_RELATIVE_URI if it is set.

**Comment by mavanidipen365** [comment]
I had done below changes to support default credential provider.
In class https://github.com/quarkiverse/quarkus-logging-cloudwatch/blob/main/runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchConfig.java

![image](https://github.com/quarkiverse/quarkus-logging-cloudwatch/assets/128300119/ce6e4d5a-4bb9-41cf-9b1b-bc012887158b)

And another change:
![image](https://github.com/quarkiverse/quarkus-logging-cloudwatch/assets/128300119/b69b79f1-5ec3-4936-9151-6df64c84937a)

**Comment by mavanidipen365** [comment]
@bennetelli would you please review the PR ?
https://github.com/quarkiverse/quarkus-logging-cloudwatch/pull/441
