### ISSUE TITLE
Fix deprecated stuff

### ISSUE THREAD

**Issue by bennetelli** [quarkiverse/quarkus-logging-cloudwatch#239]
Warning:  /home/runner/work/quarkus-logging-cloudwatch/quarkus-logging-cloudwatch/quarkus/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/Qualifiers.java:[138,24] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
Warning:  /home/runner/work/quarkus-logging-cloudwatch/quarkus-logging-cloudwatch/quarkus/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/Reflections.java:[124,29] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
Warning:  /home/runner/work/quarkus-logging-cloudwatch/quarkus-logging-cloudwatch/quarkus/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/Reflections.java:[140,23] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
Warning:  /home/runner/work/quarkus-logging-cloudwatch/quarkus-logging-cloudwatch/quarkus/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/Reflections.java:[152,23] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated
Warning:  /home/runner/work/quarkus-logging-cloudwatch/quarkus-logging-cloudwatch/quarkus/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/Reflections.java:[164,24] isAccessible() in java.lang.reflect.AccessibleObject has been deprecated

**Comment by gwenneg** [comment]
The warnings are no longer present. They were Quarkus internals anyway, nothing that can be fixed from this repo.
