### ISSUE TITLE
Releasing fails for some reason

### ISSUE THREAD

**Issue by gwenneg** [quarkiverse/quarkus-logging-cloudwatch#300]
See https://github.com/quarkiverse/quarkus-logging-cloudwatch/runs/7856793631?check_suite_focus=true

@gsmet Do you have any idea why the releasing is blocked by unstashed changes (see the end of the log)? I'm quite new at releasing quarkiverse extensions, I might have missed something. I wonder if the issue is related to the fact that I "squashed and merged" a PR earlier today instead of creating a merge commit.

**Comment by gwenneg** [comment]
@gastaldi Guillaume doesn't seem to be available today. Can you help me with my question above?

**Comment by gwenneg** [comment]
It was caused by an imports order issue on `main`. Problem solved.

**Comment by gastaldi** [comment]
Just when I was about to investigate 😄  I wonder why `mvn formatter:validate` didn't catch this in https://github.com/quarkiverse/quarkus-logging-cloudwatch/blob/main/.github/workflows/build.yml#L52?

**Comment by gwenneg** [comment]
Good question. I'll create a PR after I'm done releasing with a purposely wrong import order to check if the formatter detects the issue.

Thank for having a look!
