### ISSUE TITLE
Missing description in pom

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-logging-cloudwatch#622]
https://quarkus.io/extensions/io.quarkiverse.logging.cloudwatch/quarkus-logging-cloudwatch/ shows the parent pom's description, because the logging-cloudwatch pom does not have a description. 

<img width="228" alt="image" src="https://github.com/quarkiverse/quarkus-logging-cloudwatch/assets/11509290/148d5fe7-488f-4dca-98e2-314b016874b9">

**Comment by gwenneg** [comment]
Good catch, thanks!
