### ISSUE TITLE
Hibernate stacktrace missing in Kibana

### ISSUE THREAD

**Issue by gwenneg** [quarkiverse/quarkus-logging-cloudwatch#80]
When a failure happens during a payload processing in `notifications-backend`, [it is logged](https://github.com/RedHatInsights/notifications-backend/blob/def26b8bfd38bebb72afa1137952addc49dfbedb/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java#L68)  at `INFO` level with its cause.

In the OpenShift logs, the resulting entry looks like this:
```
2021-06-01 06:01:42,520 INFO  [com.red.clo.not.eve.EventConsumer] (vert.x-eventloop-thread-0) Could not process the payload: [...]: javax.persistence.PersistenceException: org.hibernate.HibernateException: io.vertx.pgclient.PgException: insert or update on table "notification_history" violates foreign key constraint "notification_history_endpoint_id_fkey"
```
In Kibana, the resulting entry looks like this:
```
msg=[Could not process the payload: [...], stacktrace=[  org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
```

The details about the failure cause (SQL constraint violation in the example above) are missing in Kibana.

Using [LogRecord#getThrown()](https://docs.oracle.com/en/java/javase/11/docs/api/java.logging/java/util/logging/LogRecord.html#getThrown()) in the following code may help fixing this issue:

https://github.com/quarkiverse/quarkus-logging-cloudwatch/blob/1859b69bb12b46bab0df02e3765d1e221a838c63/runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchHandler.java#L86-L96

Edit: Actually, we may want to add an additional field which would contain `LogRecord#getThrown()` instead of changing the code highlighted above. 😃

**Comment by bennetelli** [comment]
It's fixed in 1.1.2.
